export interface Country {
  /** ISO 3166-1 alpha-2 — what the API stores in `country_code`. */
  code: string;
  name_ar: string;
  name_en: string;
}

/** ISO 3166-1 alpha-2 countries, sorted by Arabic name. */
export const COUNTRIES: Country[] = [
  { code: "IS", name_ar: "آيسلندا", name_en: "Iceland" },
  { code: "ET", name_ar: "إثيوبيا", name_en: "Ethiopia" },
  { code: "AZ", name_ar: "أذربيجان", name_en: "Azerbaijan" },
  { code: "AM", name_ar: "أرمينيا", name_en: "Armenia" },
  { code: "AW", name_ar: "أروبا", name_en: "Aruba" },
  { code: "ER", name_ar: "إريتريا", name_en: "Eritrea" },
  { code: "ES", name_ar: "إسبانيا", name_en: "Spain" },
  { code: "AU", name_ar: "أستراليا", name_en: "Australia" },
  { code: "EE", name_ar: "إستونيا", name_en: "Estonia" },
  { code: "IL", name_ar: "إسرائيل", name_en: "Israel" },
  { code: "SZ", name_ar: "إسواتيني", name_en: "Eswatini" },
  { code: "AF", name_ar: "أفغانستان", name_en: "Afghanistan" },
  { code: "PS", name_ar: "الأراضي الفلسطينية", name_en: "Palestinian Territories" },
  { code: "AR", name_ar: "الأرجنتين", name_en: "Argentina" },
  { code: "JO", name_ar: "الأردن", name_en: "Jordan" },
  { code: "TF", name_ar: "الأقاليم الجنوبية الفرنسية", name_en: "French Southern Territories" },
  { code: "IO", name_ar: "الإقليم البريطاني في المحيط الهندي", name_en: "British Indian Ocean Territory" },
  { code: "EC", name_ar: "الإكوادور", name_en: "Ecuador" },
  { code: "AE", name_ar: "الإمارات العربية المتحدة", name_en: "United Arab Emirates" },
  { code: "AL", name_ar: "ألبانيا", name_en: "Albania" },
  { code: "BH", name_ar: "البحرين", name_en: "Bahrain" },
  { code: "BR", name_ar: "البرازيل", name_en: "Brazil" },
  { code: "PT", name_ar: "البرتغال", name_en: "Portugal" },
  { code: "BA", name_ar: "البوسنة والهرسك", name_en: "Bosnia & Herzegovina" },
  { code: "CZ", name_ar: "التشيك", name_en: "Czechia" },
  { code: "ME", name_ar: "الجبل الأسود", name_en: "Montenegro" },
  { code: "DZ", name_ar: "الجزائر", name_en: "Algeria" },
  { code: "DK", name_ar: "الدانمرك", name_en: "Denmark" },
  { code: "CV", name_ar: "الرأس الأخضر", name_en: "Cape Verde" },
  { code: "SV", name_ar: "السلفادور", name_en: "El Salvador" },
  { code: "SN", name_ar: "السنغال", name_en: "Senegal" },
  { code: "SD", name_ar: "السودان", name_en: "Sudan" },
  { code: "SE", name_ar: "السويد", name_en: "Sweden" },
  { code: "EH", name_ar: "الصحراء الغربية", name_en: "Western Sahara" },
  { code: "SO", name_ar: "الصومال", name_en: "Somalia" },
  { code: "CN", name_ar: "الصين", name_en: "China" },
  { code: "IQ", name_ar: "العراق", name_en: "Iraq" },
  { code: "GA", name_ar: "الغابون", name_en: "Gabon" },
  { code: "VA", name_ar: "الفاتيكان", name_en: "Vatican City" },
  { code: "PH", name_ar: "الفلبين", name_en: "Philippines" },
  { code: "CM", name_ar: "الكاميرون", name_en: "Cameroon" },
  { code: "CG", name_ar: "الكونغو - برازافيل", name_en: "Congo - Brazzaville" },
  { code: "CD", name_ar: "الكونغو - كينشاسا", name_en: "Congo - Kinshasa" },
  { code: "KW", name_ar: "الكويت", name_en: "Kuwait" },
  { code: "DE", name_ar: "ألمانيا", name_en: "Germany" },
  { code: "MA", name_ar: "المغرب", name_en: "Morocco" },
  { code: "MX", name_ar: "المكسيك", name_en: "Mexico" },
  { code: "SA", name_ar: "المملكة العربية السعودية", name_en: "Saudi Arabia" },
  { code: "GB", name_ar: "المملكة المتحدة", name_en: "United Kingdom" },
  { code: "NO", name_ar: "النرويج", name_en: "Norway" },
  { code: "AT", name_ar: "النمسا", name_en: "Austria" },
  { code: "NE", name_ar: "النيجر", name_en: "Niger" },
  { code: "IN", name_ar: "الهند", name_en: "India" },
  { code: "US", name_ar: "الولايات المتحدة", name_en: "United States" },
  { code: "JP", name_ar: "اليابان", name_en: "Japan" },
  { code: "YE", name_ar: "اليمن", name_en: "Yemen" },
  { code: "GR", name_ar: "اليونان", name_en: "Greece" },
  { code: "AQ", name_ar: "أنتاركتيكا", name_en: "Antarctica" },
  { code: "AG", name_ar: "أنتيغوا وبربودا", name_en: "Antigua & Barbuda" },
  { code: "AD", name_ar: "أندورا", name_en: "Andorra" },
  { code: "ID", name_ar: "إندونيسيا", name_en: "Indonesia" },
  { code: "AO", name_ar: "أنغولا", name_en: "Angola" },
  { code: "AI", name_ar: "أنغويلا", name_en: "Anguilla" },
  { code: "UY", name_ar: "أورغواي", name_en: "Uruguay" },
  { code: "UZ", name_ar: "أوزبكستان", name_en: "Uzbekistan" },
  { code: "UG", name_ar: "أوغندا", name_en: "Uganda" },
  { code: "UA", name_ar: "أوكرانيا", name_en: "Ukraine" },
  { code: "IR", name_ar: "إيران", name_en: "Iran" },
  { code: "IE", name_ar: "أيرلندا", name_en: "Ireland" },
  { code: "IT", name_ar: "إيطاليا", name_en: "Italy" },
  { code: "PG", name_ar: "بابوا غينيا الجديدة", name_en: "Papua New Guinea" },
  { code: "PY", name_ar: "باراغواي", name_en: "Paraguay" },
  { code: "PK", name_ar: "باكستان", name_en: "Pakistan" },
  { code: "PW", name_ar: "بالاو", name_en: "Palau" },
  { code: "BB", name_ar: "بربادوس", name_en: "Barbados" },
  { code: "BM", name_ar: "برمودا", name_en: "Bermuda" },
  { code: "BN", name_ar: "بروناي", name_en: "Brunei" },
  { code: "BE", name_ar: "بلجيكا", name_en: "Belgium" },
  { code: "BG", name_ar: "بلغاريا", name_en: "Bulgaria" },
  { code: "BZ", name_ar: "بليز", name_en: "Belize" },
  { code: "BD", name_ar: "بنغلاديش", name_en: "Bangladesh" },
  { code: "PA", name_ar: "بنما", name_en: "Panama" },
  { code: "BJ", name_ar: "بنين", name_en: "Benin" },
  { code: "BT", name_ar: "بوتان", name_en: "Bhutan" },
  { code: "BW", name_ar: "بوتسوانا", name_en: "Botswana" },
  { code: "PR", name_ar: "بورتوريكو", name_en: "Puerto Rico" },
  { code: "BF", name_ar: "بوركينا فاسو", name_en: "Burkina Faso" },
  { code: "BI", name_ar: "بوروندي", name_en: "Burundi" },
  { code: "PL", name_ar: "بولندا", name_en: "Poland" },
  { code: "BO", name_ar: "بوليفيا", name_en: "Bolivia" },
  { code: "PF", name_ar: "بولينيزيا الفرنسية", name_en: "French Polynesia" },
  { code: "PE", name_ar: "بيرو", name_en: "Peru" },
  { code: "BY", name_ar: "بيلاروس", name_en: "Belarus" },
  { code: "TH", name_ar: "تايلاند", name_en: "Thailand" },
  { code: "TW", name_ar: "تايوان", name_en: "Taiwan" },
  { code: "TM", name_ar: "تركمانستان", name_en: "Turkmenistan" },
  { code: "TR", name_ar: "تركيا", name_en: "Türkiye" },
  { code: "TT", name_ar: "ترينيداد وتوباغو", name_en: "Trinidad & Tobago" },
  { code: "TD", name_ar: "تشاد", name_en: "Chad" },
  { code: "CL", name_ar: "تشيلي", name_en: "Chile" },
  { code: "TZ", name_ar: "تنزانيا", name_en: "Tanzania" },
  { code: "TG", name_ar: "توغو", name_en: "Togo" },
  { code: "TV", name_ar: "توفالو", name_en: "Tuvalu" },
  { code: "TK", name_ar: "توكيلاو", name_en: "Tokelau" },
  { code: "TN", name_ar: "تونس", name_en: "Tunisia" },
  { code: "TO", name_ar: "تونغا", name_en: "Tonga" },
  { code: "TL", name_ar: "تيمور - ليشتي", name_en: "Timor-Leste" },
  { code: "JM", name_ar: "جامايكا", name_en: "Jamaica" },
  { code: "GI", name_ar: "جبل طارق", name_en: "Gibraltar" },
  { code: "AX", name_ar: "جزر آلاند", name_en: "Åland Islands" },
  { code: "BS", name_ar: "جزر البهاما", name_en: "Bahamas" },
  { code: "KM", name_ar: "جزر القمر", name_en: "Comoros" },
  { code: "MQ", name_ar: "جزر المارتينيك", name_en: "Martinique" },
  { code: "MV", name_ar: "جزر المالديف", name_en: "Maldives" },
  { code: "UM", name_ar: "جزر الولايات المتحدة النائية", name_en: "U.S. Outlying Islands" },
  { code: "PN", name_ar: "جزر بيتكيرن", name_en: "Pitcairn Islands" },
  { code: "TC", name_ar: "جزر توركس وكايكوس", name_en: "Turks & Caicos Islands" },
  { code: "SB", name_ar: "جزر سليمان", name_en: "Solomon Islands" },
  { code: "FO", name_ar: "جزر فارو", name_en: "Faroe Islands" },
  { code: "FK", name_ar: "جزر فوكلاند", name_en: "Falkland Islands" },
  { code: "VI", name_ar: "جزر فيرجن الأمريكية", name_en: "U.S. Virgin Islands" },
  { code: "VG", name_ar: "جزر فيرجن البريطانية", name_en: "British Virgin Islands" },
  { code: "KY", name_ar: "جزر كايمان", name_en: "Cayman Islands" },
  { code: "CK", name_ar: "جزر كوك", name_en: "Cook Islands" },
  { code: "CC", name_ar: "جزر كوكوس (كيلينغ)", name_en: "Cocos (Keeling) Islands" },
  { code: "MH", name_ar: "جزر مارشال", name_en: "Marshall Islands" },
  { code: "MP", name_ar: "جزر ماريانا الشمالية", name_en: "Northern Mariana Islands" },
  { code: "WF", name_ar: "جزر والس وفوتونا", name_en: "Wallis & Futuna" },
  { code: "BV", name_ar: "جزيرة بوفيه", name_en: "Bouvet Island" },
  { code: "CX", name_ar: "جزيرة كريسماس", name_en: "Christmas Island" },
  { code: "IM", name_ar: "جزيرة مان", name_en: "Isle of Man" },
  { code: "NF", name_ar: "جزيرة نورفولك", name_en: "Norfolk Island" },
  { code: "HM", name_ar: "جزيرة هيرد وجزر ماكدونالد", name_en: "Heard & McDonald Islands" },
  { code: "CF", name_ar: "جمهورية أفريقيا الوسطى", name_en: "Central African Republic" },
  { code: "DO", name_ar: "جمهورية الدومينيكان", name_en: "Dominican Republic" },
  { code: "ZA", name_ar: "جنوب أفريقيا", name_en: "South Africa" },
  { code: "SS", name_ar: "جنوب السودان", name_en: "South Sudan" },
  { code: "GE", name_ar: "جورجيا", name_en: "Georgia" },
  { code: "GS", name_ar: "جورجيا الجنوبية وجزر ساندويتش الجنوبية", name_en: "South Georgia & South Sandwich Islands" },
  { code: "DJ", name_ar: "جيبوتي", name_en: "Djibouti" },
  { code: "JE", name_ar: "جيرسي", name_en: "Jersey" },
  { code: "DM", name_ar: "دومينيكا", name_en: "Dominica" },
  { code: "RW", name_ar: "رواندا", name_en: "Rwanda" },
  { code: "RU", name_ar: "روسيا", name_en: "Russia" },
  { code: "RO", name_ar: "رومانيا", name_en: "Romania" },
  { code: "RE", name_ar: "روينيون", name_en: "Réunion" },
  { code: "ZM", name_ar: "زامبيا", name_en: "Zambia" },
  { code: "ZW", name_ar: "زيمبابوي", name_en: "Zimbabwe" },
  { code: "CI", name_ar: "ساحل العاج", name_en: "Côte d’Ivoire" },
  { code: "WS", name_ar: "ساموا", name_en: "Samoa" },
  { code: "AS", name_ar: "ساموا الأمريكية", name_en: "American Samoa" },
  { code: "BL", name_ar: "سان بارتليمي", name_en: "St. Barthélemy" },
  { code: "PM", name_ar: "سان بيير ومكويلون", name_en: "St. Pierre & Miquelon" },
  { code: "MF", name_ar: "سان مارتن", name_en: "St. Martin" },
  { code: "SM", name_ar: "سان مارينو", name_en: "San Marino" },
  { code: "VC", name_ar: "سانت فنسنت وجزر غرينادين", name_en: "St. Vincent & Grenadines" },
  { code: "KN", name_ar: "سانت كيتس ونيفيس", name_en: "St. Kitts & Nevis" },
  { code: "LC", name_ar: "سانت لوسيا", name_en: "St. Lucia" },
  { code: "SX", name_ar: "سانت مارتن", name_en: "Sint Maarten" },
  { code: "SH", name_ar: "سانت هيلينا", name_en: "St. Helena" },
  { code: "ST", name_ar: "ساو تومي وبرينسيبي", name_en: "São Tomé & Príncipe" },
  { code: "LK", name_ar: "سريلانكا", name_en: "Sri Lanka" },
  { code: "SJ", name_ar: "سفالبارد وجان ماين", name_en: "Svalbard & Jan Mayen" },
  { code: "SK", name_ar: "سلوفاكيا", name_en: "Slovakia" },
  { code: "SI", name_ar: "سلوفينيا", name_en: "Slovenia" },
  { code: "SG", name_ar: "سنغافورة", name_en: "Singapore" },
  { code: "SY", name_ar: "سوريا", name_en: "Syria" },
  { code: "SR", name_ar: "سورينام", name_en: "Suriname" },
  { code: "CH", name_ar: "سويسرا", name_en: "Switzerland" },
  { code: "SL", name_ar: "سيراليون", name_en: "Sierra Leone" },
  { code: "SC", name_ar: "سيشل", name_en: "Seychelles" },
  { code: "RS", name_ar: "صربيا", name_en: "Serbia" },
  { code: "TJ", name_ar: "طاجيكستان", name_en: "Tajikistan" },
  { code: "OM", name_ar: "عُمان", name_en: "Oman" },
  { code: "GM", name_ar: "غامبيا", name_en: "Gambia" },
  { code: "GH", name_ar: "غانا", name_en: "Ghana" },
  { code: "GD", name_ar: "غرينادا", name_en: "Grenada" },
  { code: "GL", name_ar: "غرينلاند", name_en: "Greenland" },
  { code: "GT", name_ar: "غواتيمالا", name_en: "Guatemala" },
  { code: "GP", name_ar: "غوادلوب", name_en: "Guadeloupe" },
  { code: "GU", name_ar: "غوام", name_en: "Guam" },
  { code: "GF", name_ar: "غويانا الفرنسية", name_en: "French Guiana" },
  { code: "GY", name_ar: "غيانا", name_en: "Guyana" },
  { code: "GG", name_ar: "غيرنزي", name_en: "Guernsey" },
  { code: "GN", name_ar: "غينيا", name_en: "Guinea" },
  { code: "GQ", name_ar: "غينيا الاستوائية", name_en: "Equatorial Guinea" },
  { code: "GW", name_ar: "غينيا بيساو", name_en: "Guinea-Bissau" },
  { code: "VU", name_ar: "فانواتو", name_en: "Vanuatu" },
  { code: "FR", name_ar: "فرنسا", name_en: "France" },
  { code: "VE", name_ar: "فنزويلا", name_en: "Venezuela" },
  { code: "FI", name_ar: "فنلندا", name_en: "Finland" },
  { code: "VN", name_ar: "فيتنام", name_en: "Vietnam" },
  { code: "FJ", name_ar: "فيجي", name_en: "Fiji" },
  { code: "CY", name_ar: "قبرص", name_en: "Cyprus" },
  { code: "QA", name_ar: "قطر", name_en: "Qatar" },
  { code: "KG", name_ar: "قيرغيزستان", name_en: "Kyrgyzstan" },
  { code: "KZ", name_ar: "كازاخستان", name_en: "Kazakhstan" },
  { code: "NC", name_ar: "كاليدونيا الجديدة", name_en: "New Caledonia" },
  { code: "HR", name_ar: "كرواتيا", name_en: "Croatia" },
  { code: "KH", name_ar: "كمبوديا", name_en: "Cambodia" },
  { code: "CA", name_ar: "كندا", name_en: "Canada" },
  { code: "CU", name_ar: "كوبا", name_en: "Cuba" },
  { code: "CW", name_ar: "كوراساو", name_en: "Curaçao" },
  { code: "KR", name_ar: "كوريا الجنوبية", name_en: "South Korea" },
  { code: "KP", name_ar: "كوريا الشمالية", name_en: "North Korea" },
  { code: "CR", name_ar: "كوستاريكا", name_en: "Costa Rica" },
  { code: "CO", name_ar: "كولومبيا", name_en: "Colombia" },
  { code: "KI", name_ar: "كيريباتي", name_en: "Kiribati" },
  { code: "KE", name_ar: "كينيا", name_en: "Kenya" },
  { code: "LV", name_ar: "لاتفيا", name_en: "Latvia" },
  { code: "LA", name_ar: "لاوس", name_en: "Laos" },
  { code: "LB", name_ar: "لبنان", name_en: "Lebanon" },
  { code: "LU", name_ar: "لوكسمبورغ", name_en: "Luxembourg" },
  { code: "LY", name_ar: "ليبيا", name_en: "Libya" },
  { code: "LR", name_ar: "ليبيريا", name_en: "Liberia" },
  { code: "LT", name_ar: "ليتوانيا", name_en: "Lithuania" },
  { code: "LI", name_ar: "ليختنشتاين", name_en: "Liechtenstein" },
  { code: "LS", name_ar: "ليسوتو", name_en: "Lesotho" },
  { code: "MT", name_ar: "مالطا", name_en: "Malta" },
  { code: "ML", name_ar: "مالي", name_en: "Mali" },
  { code: "MY", name_ar: "ماليزيا", name_en: "Malaysia" },
  { code: "YT", name_ar: "مايوت", name_en: "Mayotte" },
  { code: "MG", name_ar: "مدغشقر", name_en: "Madagascar" },
  { code: "EG", name_ar: "مصر", name_en: "Egypt" },
  { code: "MK", name_ar: "مقدونيا الشمالية", name_en: "North Macedonia" },
  { code: "MW", name_ar: "ملاوي", name_en: "Malawi" },
  { code: "MO", name_ar: "منطقة ماكاو الإدارية الخاصة", name_en: "Macao SAR China" },
  { code: "MN", name_ar: "منغوليا", name_en: "Mongolia" },
  { code: "MR", name_ar: "موريتانيا", name_en: "Mauritania" },
  { code: "MU", name_ar: "موريشيوس", name_en: "Mauritius" },
  { code: "MZ", name_ar: "موزمبيق", name_en: "Mozambique" },
  { code: "MD", name_ar: "مولدوفا", name_en: "Moldova" },
  { code: "MC", name_ar: "موناكو", name_en: "Monaco" },
  { code: "MS", name_ar: "مونتسرات", name_en: "Montserrat" },
  { code: "MM", name_ar: "ميانمار (بورما)", name_en: "Myanmar (Burma)" },
  { code: "FM", name_ar: "ميكرونيزيا", name_en: "Micronesia" },
  { code: "NA", name_ar: "ناميبيا", name_en: "Namibia" },
  { code: "NR", name_ar: "ناورو", name_en: "Nauru" },
  { code: "NP", name_ar: "نيبال", name_en: "Nepal" },
  { code: "NG", name_ar: "نيجيريا", name_en: "Nigeria" },
  { code: "NI", name_ar: "نيكاراغوا", name_en: "Nicaragua" },
  { code: "NZ", name_ar: "نيوزيلندا", name_en: "New Zealand" },
  { code: "NU", name_ar: "نيوي", name_en: "Niue" },
  { code: "HT", name_ar: "هايتي", name_en: "Haiti" },
  { code: "HN", name_ar: "هندوراس", name_en: "Honduras" },
  { code: "HU", name_ar: "هنغاريا", name_en: "Hungary" },
  { code: "NL", name_ar: "هولندا", name_en: "Netherlands" },
  { code: "BQ", name_ar: "هولندا الكاريبية", name_en: "Caribbean Netherlands" },
  { code: "HK", name_ar: "هونغ كونغ الصينية (منطقة إدارية خاصة)", name_en: "Hong Kong SAR China" },
];
